name: package

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm i -g @vscode/vsce
      - run: vsce package
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-calliper
          path: '*.vsix'
